services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev
    container_name: keycloak-local
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    restart: unless-stopped
